### ISSUE TITLE
Arisistemas

### ISSUE THREAD

**Issue by 23620030** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620030#5]
[ejercicios ARIADNA BELEN BERNABE JUAREZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620030/files/12571163/ejercicios.ARIADNA.BELEN.BERNABE.JUAREZ.pdf)

**Comment by Felix-Angel** [comment]
PORTADA 25%
PROCEDIMIENTO 25%
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25%
RESULTADOS Y CONCLUSIONES ( NO CUENTA CON LAS LINEAS DE TEXTO DE LA CONCLUSION, CUENTA CON 10) 22%
CALIFICACION: 97/100
CALIFICADO POR: "EQUIPO DE MAYRA, DIEGO, DANIEL, FELIX"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
